spring:
  datasource:
    url: jdbc:mysql://192.168.0.8:2506/oa?useSSL=false
    username: root
    password: 123.abc.X
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    zool.firefly.dao: debug

server:
  port: 8080