spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?useSSL=false
    username: root
    password: root
    driver: com.mysql.jdbc.Driver
    callSettersOnNulls: true


logging:
  level:
    zool.firefly.dao: debug
